[project]
name = "cloudformation-deploy-to-s3"
version = "0.1.0"
description = "CloudFormation Deploy to S3 "
readme = "README.md"
requires-python = "==3.13.7"
dependencies = [
    "boto3>=1.40.19",
    "requests>=2.32.5",
]
